name = "UndoDDDX"
uid = "11111111-8DDE-416A-9D76-AACCAA170000"
version = 1
copyright = "by EntropyWins"
description = "Re-enable building RAS SACUs directly from a quantum gateway"
author = "EntropyWins"
selectable = true
ui_only = false
url = "https://github.com/JeroenDeDauw/UndoDDDX"
icon = "/mods/UndoDDDX/icon.png"
