name = "UndoDDDX"
uid = "11111111-8dde-416a-9d76-aaccaa171b00"
version = 2
copyright = "by EntropyWins"
description = "Enable RAS SACUs"
author = "EntropyWins"
selectable = true
ui_only = false
url = "https://github.com/JeroenDeDauw/UndoDDDX"
icon = "/mods/UndoDDDX/icon.png"